
version: '2'

services:

  orderer.pdt.com:
    container_name: orderer.pdt.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/pdt.com/orderers/orderer.pdt.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/pdt.com/orderers/orderer.pdt.com/tls/:/var/hyperledger/orderer/tls
        - orderer.pdt.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.pdt.com:
    container_name: peer0.org1.pdt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.pdt.com
      - CORE_PEER_ADDRESS=peer0.org1.pdt.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.pdt.com:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.pdt.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.pdt.com:11051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        # - ../crypto-config/peerOrganizations/org1.pdt.com/users/Admin@org1.pdt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.pdt.com/peers/peer0.org1.pdt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.pdt.com/peers/peer0.org1.pdt.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - peer0.org1.pdt.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer0.org2.pdt.com:
    container_name: peer0.org2.pdt.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.pdt.com
      - CORE_PEER_ADDRESS=peer0.org2.pdt.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.pdt.com:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.pdt.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.pdt.com:12051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.pdt.com/peers/peer0.org2.pdt.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.pdt.com/peers/peer0.org2.pdt.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.pdt.com:/var/hyperledger/production

    ports:
      - 12051:12051

  