# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: pdt.com
    EnableNodeOUs: true
    # CA:
    #   OrganizationalUnitIdentifier: admin 
    Specs:
      - Hostname: orderer
      # - Hostname: orderer2
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # product
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.pdt.com
    EnableNodeOUs: true
    Template:
      Count: 1
    
  - Name: Org2
    Domain: org2.pdt.com
    EnableNodeOUs: true
    Template:
      Count: 1
       
  
