version: '2'

volumes:
  orderer.pdt.com:
  peer0.org1.pdt.com:
  peer0.org2.pdt.com:
 

networks:
  byfn:

services:

  orderer.pdt.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.pdt.com
    container_name: orderer.pdt.com
    networks:
      - byfn

  peer0.org1.pdt.com:
    container_name: peer0.org1.pdt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.pdt.com
    networks:
      - byfn

  peer0.org2.pdt.com:
    container_name: peer0.org2.pdt.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.pdt.com
    networks:
      - byfn
            

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.pdt.com:11051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99 
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pdt.com/peers/peer0.org1.pdt.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pdt.com/peers/peer0.org1.pdt.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pdt.com/peers/peer0.org1.pdt.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pdt.com/users/Admin@org1.pdt.com/msp/
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.pdt.com
      - peer0.org1.pdt.com
      - peer0.org2.pdt.com
     
    networks:
      - byfn
